#!/bin/sh

sbatch --partition=All --job-name=ppo_1 --cpus-per-task=4 --output=slurm/slurm1.out ppo_fed.sh 0 0 0 0
sbatch --partition=All --job-name=ppo_2 --cpus-per-task=4 --output=slurm/slurm2.out ppo_fed.sh 0 0 0 1
sbatch --partition=All --job-name=ppo_3 --cpus-per-task=4 --output=slurm/slurm3.out ppo_fed.sh 0 0 1 0
sbatch --partition=All --job-name=ppo_4 --cpus-per-task=4 --output=slurm/slurm4.out ppo_fed.sh 0 0 1 1
sbatch --partition=All --job-name=ppo_5 --cpus-per-task=4 --output=slurm/slurm5.out ppo_fed.sh 0 0 2 0
sbatch --partition=All --job-name=ppo_6 --cpus-per-task=4 --output=slurm/slurm6.out ppo_fed.sh 0 0 2 1
sbatch --partition=All --job-name=ppo_7 --cpus-per-task=4 --output=slurm/slurm7.out ppo_fed.sh 0 1 0 0
sbatch --partition=All --job-name=ppo_8 --cpus-per-task=4 --output=slurm/slurm8.out ppo_fed.sh 0 1 0 1
sbatch --partition=All --job-name=ppo_9 --cpus-per-task=4 --output=slurm/slurm9.out ppo_fed.sh 0 1 1 0
sbatch --partition=All --job-name=ppo_10 --cpus-per-task=4 --output=slurm/slurm10.out ppo_fed.sh 0 1 1 1
sbatch --partition=All --job-name=ppo_11 --cpus-per-task=4 --output=slurm/slurm11.out ppo_fed.sh 0 1 2 0
sbatch --partition=All --job-name=ppo_12 --cpus-per-task=4 --output=slurm/slurm12.out ppo_fed.sh 0 1 2 1
sbatch --partition=All --job-name=ppo_13 --cpus-per-task=4 --output=slurm/slurm13.out ppo_fed.sh 0 2 0 0
sbatch --partition=All --job-name=ppo_14 --cpus-per-task=4 --output=slurm/slurm14.out ppo_fed.sh 0 2 0 1
sbatch --partition=All --job-name=ppo_15 --cpus-per-task=4 --output=slurm/slurm15.out ppo_fed.sh 0 2 1 0
sbatch --partition=All --job-name=ppo_16 --cpus-per-task=4 --output=slurm/slurm16.out ppo_fed.sh 0 2 1 1
sbatch --partition=All --job-name=ppo_17 --cpus-per-task=4 --output=slurm/slurm17.out ppo_fed.sh 0 2 2 0
sbatch --partition=All --job-name=ppo_18 --cpus-per-task=4 --output=slurm/slurm18.out ppo_fed.sh 0 2 2 1
sbatch --partition=All --job-name=ppo_19 --cpus-per-task=4 --output=slurm/slurm19.out ppo_fed.sh 0 3 0 0
sbatch --partition=All --job-name=ppo_20 --cpus-per-task=4 --output=slurm/slurm20.out ppo_fed.sh 0 3 0 1
sbatch --partition=All --job-name=ppo_21 --cpus-per-task=4 --output=slurm/slurm21.out ppo_fed.sh 0 3 1 0
sbatch --partition=All --job-name=ppo_22 --cpus-per-task=4 --output=slurm/slurm22.out ppo_fed.sh 0 3 1 1
sbatch --partition=All --job-name=ppo_23 --cpus-per-task=4 --output=slurm/slurm23.out ppo_fed.sh 0 3 2 0
sbatch --partition=All --job-name=ppo_24 --cpus-per-task=4 --output=slurm/slurm24.out ppo_fed.sh 0 3 2 1
sbatch --partition=All --job-name=ppo_25 --cpus-per-task=4 --output=slurm/slurm25.out ppo_fed.sh 0 4 0 0
sbatch --partition=All --job-name=ppo_26 --cpus-per-task=4 --output=slurm/slurm26.out ppo_fed.sh 0 4 0 1
sbatch --partition=All --job-name=ppo_27 --cpus-per-task=4 --output=slurm/slurm27.out ppo_fed.sh 0 4 1 0
sbatch --partition=All --job-name=ppo_28 --cpus-per-task=4 --output=slurm/slurm28.out ppo_fed.sh 0 4 1 1
sbatch --partition=All --job-name=ppo_29 --cpus-per-task=4 --output=slurm/slurm29.out ppo_fed.sh 0 4 2 0
sbatch --partition=All --job-name=ppo_30 --cpus-per-task=4 --output=slurm/slurm30.out ppo_fed.sh 0 4 2 1
sbatch --partition=All --job-name=ppo_31 --cpus-per-task=4 --output=slurm/slurm31.out ppo_fed.sh 0 5 0 0
sbatch --partition=All --job-name=ppo_32 --cpus-per-task=4 --output=slurm/slurm32.out ppo_fed.sh 0 5 0 1
sbatch --partition=All --job-name=ppo_33 --cpus-per-task=4 --output=slurm/slurm33.out ppo_fed.sh 0 5 1 0
sbatch --partition=All --job-name=ppo_34 --cpus-per-task=4 --output=slurm/slurm34.out ppo_fed.sh 0 5 1 1
sbatch --partition=All --job-name=ppo_35 --cpus-per-task=4 --output=slurm/slurm35.out ppo_fed.sh 0 5 2 0
sbatch --partition=All --job-name=ppo_36 --cpus-per-task=4 --output=slurm/slurm36.out ppo_fed.sh 0 5 2 1
sbatch --partition=All --job-name=ppo_37 --cpus-per-task=4 --output=slurm/slurm37.out ppo_fed.sh 1 0 0 0
sbatch --partition=All --job-name=ppo_38 --cpus-per-task=4 --output=slurm/slurm38.out ppo_fed.sh 1 0 0 1
sbatch --partition=All --job-name=ppo_39 --cpus-per-task=4 --output=slurm/slurm39.out ppo_fed.sh 1 0 1 0
sbatch --partition=All --job-name=ppo_40 --cpus-per-task=4 --output=slurm/slurm40.out ppo_fed.sh 1 0 1 1
sbatch --partition=All --job-name=ppo_41 --cpus-per-task=4 --output=slurm/slurm41.out ppo_fed.sh 1 0 2 0
sbatch --partition=All --job-name=ppo_42 --cpus-per-task=4 --output=slurm/slurm42.out ppo_fed.sh 1 0 2 1
sbatch --partition=All --job-name=ppo_43 --cpus-per-task=4 --output=slurm/slurm43.out ppo_fed.sh 1 1 0 0
sbatch --partition=All --job-name=ppo_44 --cpus-per-task=4 --output=slurm/slurm44.out ppo_fed.sh 1 1 0 1
sbatch --partition=All --job-name=ppo_45 --cpus-per-task=4 --output=slurm/slurm45.out ppo_fed.sh 1 1 1 0
sbatch --partition=All --job-name=ppo_46 --cpus-per-task=4 --output=slurm/slurm46.out ppo_fed.sh 1 1 1 1
sbatch --partition=All --job-name=ppo_47 --cpus-per-task=4 --output=slurm/slurm47.out ppo_fed.sh 1 1 2 0
sbatch --partition=All --job-name=ppo_48 --cpus-per-task=4 --output=slurm/slurm48.out ppo_fed.sh 1 1 2 1
sbatch --partition=All --job-name=ppo_49 --cpus-per-task=4 --output=slurm/slurm49.out ppo_fed.sh 1 2 0 0
sbatch --partition=All --job-name=ppo_50 --cpus-per-task=4 --output=slurm/slurm50.out ppo_fed.sh 1 2 0 1
sbatch --partition=All --job-name=ppo_51 --cpus-per-task=4 --output=slurm/slurm51.out ppo_fed.sh 1 2 1 0
sbatch --partition=All --job-name=ppo_52 --cpus-per-task=4 --output=slurm/slurm52.out ppo_fed.sh 1 2 1 1
sbatch --partition=All --job-name=ppo_53 --cpus-per-task=4 --output=slurm/slurm53.out ppo_fed.sh 1 2 2 0
sbatch --partition=All --job-name=ppo_54 --cpus-per-task=4 --output=slurm/slurm54.out ppo_fed.sh 1 2 2 1
sbatch --partition=All --job-name=ppo_55 --cpus-per-task=4 --output=slurm/slurm55.out ppo_fed.sh 1 3 0 0
sbatch --partition=All --job-name=ppo_56 --cpus-per-task=4 --output=slurm/slurm56.out ppo_fed.sh 1 3 0 1
sbatch --partition=All --job-name=ppo_57 --cpus-per-task=4 --output=slurm/slurm57.out ppo_fed.sh 1 3 1 0
sbatch --partition=All --job-name=ppo_58 --cpus-per-task=4 --output=slurm/slurm58.out ppo_fed.sh 1 3 1 1
sbatch --partition=All --job-name=ppo_59 --cpus-per-task=4 --output=slurm/slurm59.out ppo_fed.sh 1 3 2 0
sbatch --partition=All --job-name=ppo_60 --cpus-per-task=4 --output=slurm/slurm60.out ppo_fed.sh 1 3 2 1
sbatch --partition=All --job-name=ppo_61 --cpus-per-task=4 --output=slurm/slurm61.out ppo_fed.sh 1 4 0 0
sbatch --partition=All --job-name=ppo_62 --cpus-per-task=4 --output=slurm/slurm62.out ppo_fed.sh 1 4 0 1
sbatch --partition=All --job-name=ppo_63 --cpus-per-task=4 --output=slurm/slurm63.out ppo_fed.sh 1 4 1 0
sbatch --partition=All --job-name=ppo_64 --cpus-per-task=4 --output=slurm/slurm64.out ppo_fed.sh 1 4 1 1
sbatch --partition=All --job-name=ppo_65 --cpus-per-task=4 --output=slurm/slurm65.out ppo_fed.sh 1 4 2 0
sbatch --partition=All --job-name=ppo_66 --cpus-per-task=4 --output=slurm/slurm66.out ppo_fed.sh 1 4 2 1
sbatch --partition=All --job-name=ppo_67 --cpus-per-task=4 --output=slurm/slurm67.out ppo_fed.sh 1 5 0 0
sbatch --partition=All --job-name=ppo_68 --cpus-per-task=4 --output=slurm/slurm68.out ppo_fed.sh 1 5 0 1
sbatch --partition=All --job-name=ppo_69 --cpus-per-task=4 --output=slurm/slurm69.out ppo_fed.sh 1 5 1 0
sbatch --partition=All --job-name=ppo_70 --cpus-per-task=4 --output=slurm/slurm70.out ppo_fed.sh 1 5 1 1
sbatch --partition=All --job-name=ppo_71 --cpus-per-task=4 --output=slurm/slurm71.out ppo_fed.sh 1 5 2 0
sbatch --partition=All --job-name=ppo_72 --cpus-per-task=4 --output=slurm/slurm72.out ppo_fed.sh 1 5 2 1
sbatch --partition=All --job-name=ppo_73 --cpus-per-task=4 --output=slurm/slurm73.out ppo_fed.sh 2 0 0 0
sbatch --partition=All --job-name=ppo_74 --cpus-per-task=4 --output=slurm/slurm74.out ppo_fed.sh 2 0 0 1
sbatch --partition=All --job-name=ppo_75 --cpus-per-task=4 --output=slurm/slurm75.out ppo_fed.sh 2 0 1 0
sbatch --partition=All --job-name=ppo_76 --cpus-per-task=4 --output=slurm/slurm76.out ppo_fed.sh 2 0 1 1
sbatch --partition=All --job-name=ppo_77 --cpus-per-task=4 --output=slurm/slurm77.out ppo_fed.sh 2 0 2 0
sbatch --partition=All --job-name=ppo_78 --cpus-per-task=4 --output=slurm/slurm78.out ppo_fed.sh 2 0 2 1
sbatch --partition=All --job-name=ppo_79 --cpus-per-task=4 --output=slurm/slurm79.out ppo_fed.sh 2 1 0 0
sbatch --partition=All --job-name=ppo_80 --cpus-per-task=4 --output=slurm/slurm80.out ppo_fed.sh 2 1 0 1
sbatch --partition=All --job-name=ppo_81 --cpus-per-task=4 --output=slurm/slurm81.out ppo_fed.sh 2 1 1 0
sbatch --partition=All --job-name=ppo_82 --cpus-per-task=4 --output=slurm/slurm82.out ppo_fed.sh 2 1 1 1
sbatch --partition=All --job-name=ppo_83 --cpus-per-task=4 --output=slurm/slurm83.out ppo_fed.sh 2 1 2 0
sbatch --partition=All --job-name=ppo_84 --cpus-per-task=4 --output=slurm/slurm84.out ppo_fed.sh 2 1 2 1
sbatch --partition=All --job-name=ppo_85 --cpus-per-task=4 --output=slurm/slurm85.out ppo_fed.sh 2 2 0 0
sbatch --partition=All --job-name=ppo_86 --cpus-per-task=4 --output=slurm/slurm86.out ppo_fed.sh 2 2 0 1
sbatch --partition=All --job-name=ppo_87 --cpus-per-task=4 --output=slurm/slurm87.out ppo_fed.sh 2 2 1 0
sbatch --partition=All --job-name=ppo_88 --cpus-per-task=4 --output=slurm/slurm88.out ppo_fed.sh 2 2 1 1
sbatch --partition=All --job-name=ppo_89 --cpus-per-task=4 --output=slurm/slurm89.out ppo_fed.sh 2 2 2 0
sbatch --partition=All --job-name=ppo_90 --cpus-per-task=4 --output=slurm/slurm90.out ppo_fed.sh 2 2 2 1
sbatch --partition=All --job-name=ppo_91 --cpus-per-task=4 --output=slurm/slurm91.out ppo_fed.sh 2 3 0 0
sbatch --partition=All --job-name=ppo_92 --cpus-per-task=4 --output=slurm/slurm92.out ppo_fed.sh 2 3 0 1
sbatch --partition=All --job-name=ppo_93 --cpus-per-task=4 --output=slurm/slurm93.out ppo_fed.sh 2 3 1 0
sbatch --partition=All --job-name=ppo_94 --cpus-per-task=4 --output=slurm/slurm94.out ppo_fed.sh 2 3 1 1
sbatch --partition=All --job-name=ppo_95 --cpus-per-task=4 --output=slurm/slurm95.out ppo_fed.sh 2 3 2 0
sbatch --partition=All --job-name=ppo_96 --cpus-per-task=4 --output=slurm/slurm96.out ppo_fed.sh 2 3 2 1
sbatch --partition=All --job-name=ppo_97 --cpus-per-task=4 --output=slurm/slurm97.out ppo_fed.sh 2 4 0 0
sbatch --partition=All --job-name=ppo_98 --cpus-per-task=4 --output=slurm/slurm98.out ppo_fed.sh 2 4 0 1
sbatch --partition=All --job-name=ppo_99 --cpus-per-task=4 --output=slurm/slurm99.out ppo_fed.sh 2 4 1 0
sbatch --partition=All --job-name=ppo_100 --cpus-per-task=4 --output=slurm/slurm100.out ppo_fed.sh 2 4 1 1
sbatch --partition=All --job-name=ppo_101 --cpus-per-task=4 --output=slurm/slurm101.out ppo_fed.sh 2 4 2 0
sbatch --partition=All --job-name=ppo_102 --cpus-per-task=4 --output=slurm/slurm102.out ppo_fed.sh 2 4 2 1
sbatch --partition=All --job-name=ppo_103 --cpus-per-task=4 --output=slurm/slurm103.out ppo_fed.sh 2 5 0 0
sbatch --partition=All --job-name=ppo_104 --cpus-per-task=4 --output=slurm/slurm104.out ppo_fed.sh 2 5 0 1
sbatch --partition=All --job-name=ppo_105 --cpus-per-task=4 --output=slurm/slurm105.out ppo_fed.sh 2 5 1 0
sbatch --partition=All --job-name=ppo_106 --cpus-per-task=4 --output=slurm/slurm106.out ppo_fed.sh 2 5 1 1
sbatch --partition=All --job-name=ppo_107 --cpus-per-task=4 --output=slurm/slurm107.out ppo_fed.sh 2 5 2 0
sbatch --partition=All --job-name=ppo_108 --cpus-per-task=4 --output=slurm/slurm108.out ppo_fed.sh 2 5 2 1
sbatch --partition=All --job-name=ppo_109 --cpus-per-task=4 --output=slurm/slurm109.out ppo_fed.sh 3 0 0 0
sbatch --partition=All --job-name=ppo_110 --cpus-per-task=4 --output=slurm/slurm110.out ppo_fed.sh 3 0 0 1
sbatch --partition=All --job-name=ppo_111 --cpus-per-task=4 --output=slurm/slurm111.out ppo_fed.sh 3 0 1 0
sbatch --partition=All --job-name=ppo_112 --cpus-per-task=4 --output=slurm/slurm112.out ppo_fed.sh 3 0 1 1
sbatch --partition=All --job-name=ppo_113 --cpus-per-task=4 --output=slurm/slurm113.out ppo_fed.sh 3 0 2 0
sbatch --partition=All --job-name=ppo_114 --cpus-per-task=4 --output=slurm/slurm114.out ppo_fed.sh 3 0 2 1
sbatch --partition=All --job-name=ppo_115 --cpus-per-task=4 --output=slurm/slurm115.out ppo_fed.sh 3 1 0 0
sbatch --partition=All --job-name=ppo_116 --cpus-per-task=4 --output=slurm/slurm116.out ppo_fed.sh 3 1 0 1
sbatch --partition=All --job-name=ppo_117 --cpus-per-task=4 --output=slurm/slurm117.out ppo_fed.sh 3 1 1 0
sbatch --partition=All --job-name=ppo_118 --cpus-per-task=4 --output=slurm/slurm118.out ppo_fed.sh 3 1 1 1
sbatch --partition=All --job-name=ppo_119 --cpus-per-task=4 --output=slurm/slurm119.out ppo_fed.sh 3 1 2 0
sbatch --partition=All --job-name=ppo_120 --cpus-per-task=4 --output=slurm/slurm120.out ppo_fed.sh 3 1 2 1
sbatch --partition=All --job-name=ppo_121 --cpus-per-task=4 --output=slurm/slurm121.out ppo_fed.sh 3 2 0 0
sbatch --partition=All --job-name=ppo_122 --cpus-per-task=4 --output=slurm/slurm122.out ppo_fed.sh 3 2 0 1
sbatch --partition=All --job-name=ppo_123 --cpus-per-task=4 --output=slurm/slurm123.out ppo_fed.sh 3 2 1 0
sbatch --partition=All --job-name=ppo_124 --cpus-per-task=4 --output=slurm/slurm124.out ppo_fed.sh 3 2 1 1
sbatch --partition=All --job-name=ppo_125 --cpus-per-task=4 --output=slurm/slurm125.out ppo_fed.sh 3 2 2 0
sbatch --partition=All --job-name=ppo_126 --cpus-per-task=4 --output=slurm/slurm126.out ppo_fed.sh 3 2 2 1
sbatch --partition=All --job-name=ppo_127 --cpus-per-task=4 --output=slurm/slurm127.out ppo_fed.sh 3 3 0 0
sbatch --partition=All --job-name=ppo_128 --cpus-per-task=4 --output=slurm/slurm128.out ppo_fed.sh 3 3 0 1
sbatch --partition=All --job-name=ppo_129 --cpus-per-task=4 --output=slurm/slurm129.out ppo_fed.sh 3 3 1 0
sbatch --partition=All --job-name=ppo_130 --cpus-per-task=4 --output=slurm/slurm130.out ppo_fed.sh 3 3 1 1
sbatch --partition=All --job-name=ppo_131 --cpus-per-task=4 --output=slurm/slurm131.out ppo_fed.sh 3 3 2 0
sbatch --partition=All --job-name=ppo_132 --cpus-per-task=4 --output=slurm/slurm132.out ppo_fed.sh 3 3 2 1
sbatch --partition=All --job-name=ppo_133 --cpus-per-task=4 --output=slurm/slurm133.out ppo_fed.sh 3 4 0 0
sbatch --partition=All --job-name=ppo_134 --cpus-per-task=4 --output=slurm/slurm134.out ppo_fed.sh 3 4 0 1
sbatch --partition=All --job-name=ppo_135 --cpus-per-task=4 --output=slurm/slurm135.out ppo_fed.sh 3 4 1 0
sbatch --partition=All --job-name=ppo_136 --cpus-per-task=4 --output=slurm/slurm136.out ppo_fed.sh 3 4 1 1
sbatch --partition=All --job-name=ppo_137 --cpus-per-task=4 --output=slurm/slurm137.out ppo_fed.sh 3 4 2 0
sbatch --partition=All --job-name=ppo_138 --cpus-per-task=4 --output=slurm/slurm138.out ppo_fed.sh 3 4 2 1
sbatch --partition=All --job-name=ppo_139 --cpus-per-task=4 --output=slurm/slurm139.out ppo_fed.sh 3 5 0 0
sbatch --partition=All --job-name=ppo_140 --cpus-per-task=4 --output=slurm/slurm140.out ppo_fed.sh 3 5 0 1
sbatch --partition=All --job-name=ppo_141 --cpus-per-task=4 --output=slurm/slurm141.out ppo_fed.sh 3 5 1 0
sbatch --partition=All --job-name=ppo_142 --cpus-per-task=4 --output=slurm/slurm142.out ppo_fed.sh 3 5 1 1
sbatch --partition=All --job-name=ppo_143 --cpus-per-task=4 --output=slurm/slurm143.out ppo_fed.sh 3 5 2 0
sbatch --partition=All --job-name=ppo_144 --cpus-per-task=4 --output=slurm/slurm144.out ppo_fed.sh 3 5 2 1

squeue -u jensenj
squeue -u jensenj -h -t pending,running -r | wc -l
